#!/bin/bash

main=~/.tvrenamer
old_over=~/.tvrenameroverrides
new_prefs=${main}/prefs.xml
new_over=${main}/overrides.xml
temp=~/tvr-temp.txt

if [ -d ${main} ]
then
  echo "Moving from new to old"
  /bin/rm -f ${old_over}
  /bin/mv -i ${new_over} ${old_over}
  /bin/mv ${new_prefs} ${temp}
  /bin/rmdir ${main}
  /bin/mv ${temp} ${main}
else
  echo "Moving from old to new"
  /bin/mv ${main} ${temp}
  /bin/mkdir ${main}
  /bin/mv ${temp} ${new_prefs}
  /bin/mv ${old_over} ${new_over}
fi

